import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import * as bcrypt from 'bcrypt';
import { User } from '../users/entities/user.entity';
import { UserRole } from '../users/enums/user-role.enum';

// Lade .env Datei
dotenv.config();

const escorts = [
  {
    email: 'anna.berlin@test.com',
    username: 'anna_berlin',
    firstName: 'Anna',
    lastName: 'Müller',
    birthDate: '1995-03-15',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 168,
    weight: 58,
    bodyType: 'Schlank',
    cupSize: 'B',
    hairColor: 'Blond',
    hairLength: 'Lang',
    eyeColor: 'Blau',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: true,
    isSmoker: false,
    description: 'Hallo, ich bin Anna aus Berlin und freue mich auf nette Begegnungen.',
    latitude: 52.5200,
    longitude: 13.4050, // Berlin
  },
  {
    email: 'maria.muenchen@test.com',
    username: 'maria_munich',
    firstName: 'Maria',
    lastName: 'Schmidt',
    birthDate: '1992-07-22',
    nationalities: ['Deutsch', 'Italienisch'],
    languages: ['Deutsch', 'Italienisch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 172,
    weight: 62,
    bodyType: 'Athletisch',
    cupSize: 'C',
    hairColor: 'Braun',
    hairLength: 'Schulterlang',
    eyeColor: 'Braun',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: false,
    isSmoker: false,
    description: 'Ciao! Ich liebe das Leben und neue Erfahrungen.',
    latitude: 48.1351,
    longitude: 11.5820, // München
  },
  {
    email: 'sophie.hamburg@test.com',
    username: 'sophie_hamburg',
    firstName: 'Sophie',
    lastName: 'Weber',
    birthDate: '1998-11-08',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch', 'Französisch'],
    type: 'Westeuropäisch',
    height: 165,
    weight: 55,
    bodyType: 'Sehr schlank',
    cupSize: 'A',
    hairColor: 'Blond',
    hairLength: 'Kurz',
    eyeColor: 'Grün',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: false,
    isSmoker: false,
    description: 'Hey! Ich bin Sophie und liebe spannende Gespräche.',
    latitude: 53.5511,
    longitude: 9.9937, // Hamburg
  },
  {
    email: 'elena.koeln@test.com',
    username: 'elena_cologne',
    firstName: 'Elena',
    lastName: 'Popov',
    birthDate: '1994-05-30',
    nationalities: ['Russisch', 'Deutsch'],
    languages: ['Russisch', 'Deutsch', 'Englisch'],
    type: 'Osteuropäisch',
    height: 175,
    weight: 65,
    bodyType: 'Athletisch',
    cupSize: 'D',
    hairColor: 'Schwarz',
    hairLength: 'Lang',
    eyeColor: 'Grau',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: true,
    isSmoker: true,
    description: 'Привет! Ich bin Elena, temperamentvoll und lebenslustig.',
    latitude: 50.9375,
    longitude: 6.9603, // Köln
  },
  {
    email: 'jasmin.frankfurt@test.com',
    username: 'jasmin_frankfurt',
    firstName: 'Jasmin',
    lastName: 'Hassan',
    birthDate: '1996-09-12',
    nationalities: ['Türkisch', 'Deutsch'],
    languages: ['Türkisch', 'Deutsch', 'Englisch'],
    type: 'Orientalisch',
    height: 170,
    weight: 60,
    bodyType: 'Mittel',
    cupSize: 'C',
    hairColor: 'Schwarz',
    hairLength: 'Sehr lang',
    eyeColor: 'Braun',
    intimateHair: 'Behaart',
    hasTattoos: false,
    hasPiercings: true,
    isSmoker: false,
    description: 'Merhaba! Ich bin Jasmin und freue mich auf dich.',
    latitude: 50.1109,
    longitude: 8.6821, // Frankfurt
  },
  {
    email: 'lisa.stuttgart@test.com',
    username: 'lisa_stuttgart',
    firstName: 'Lisa',
    lastName: 'Meyer',
    birthDate: '1993-02-18',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 163,
    weight: 52,
    bodyType: 'Schlank',
    cupSize: 'B',
    hairColor: 'Braun',
    hairLength: 'Schulterlang',
    eyeColor: 'Blau',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: false,
    isSmoker: false,
    description: 'Hi, ich bin Lisa - natürlich und unkompliziert.',
    latitude: 48.7758,
    longitude: 9.1829, // Stuttgart
  },
  {
    email: 'nina.duesseldorf@test.com',
    username: 'nina_duesseldorf',
    firstName: 'Nina',
    lastName: 'Klein',
    birthDate: '1997-06-25',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch', 'Spanisch'],
    type: 'Westeuropäisch',
    height: 178,
    weight: 68,
    bodyType: 'Mittel',
    cupSize: 'DD',
    hairColor: 'Rot',
    hairLength: 'Lang',
    eyeColor: 'Grün',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: true,
    isSmoker: false,
    description: 'Hola! Ich bin Nina und liebe Abenteuer.',
    latitude: 51.2277,
    longitude: 6.7735, // Düsseldorf
  },
  {
    email: 'carmen.barcelona@test.com',
    username: 'carmen_barcelona',
    firstName: 'Carmen',
    lastName: 'Rodriguez',
    birthDate: '1991-04-10',
    nationalities: ['Spanisch'],
    languages: ['Spanisch', 'Englisch', 'Deutsch'],
    type: 'Latina',
    height: 167,
    weight: 59,
    bodyType: 'Kurvig',
    cupSize: 'C',
    hairColor: 'Schwarz',
    hairLength: 'Lang',
    eyeColor: 'Braun',
    intimateHair: 'Behaart',
    hasTattoos: true,
    hasPiercings: false,
    isSmoker: true,
    description: '¡Hola! Soy Carmen, apasionada y divertida.',
    latitude: 41.3851,
    longitude: 2.1734, // Barcelona (Spanien für Variety)
  },
  {
    email: 'yuki.tokyo@test.com',
    username: 'yuki_tokyo',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    birthDate: '1999-12-05',
    nationalities: ['Japanisch'],
    languages: ['Japanisch', 'Englisch'],
    type: 'Asiatisch',
    height: 158,
    weight: 48,
    bodyType: 'Sehr schlank',
    cupSize: 'A',
    hairColor: 'Schwarz',
    hairLength: 'Schulterlang',
    eyeColor: 'Braun',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: false,
    isSmoker: false,
    description: 'Konnichiwa! I am Yuki from Tokyo.',
    latitude: 35.6762,
    longitude: 139.6503, // Tokyo (für Variety)
  },
  {
    email: 'sarah.dortmund@test.com',
    username: 'sarah_dortmund',
    firstName: 'Sarah',
    lastName: 'Fischer',
    birthDate: '1990-08-14',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 169,
    weight: 63,
    bodyType: 'Mittel',
    cupSize: 'C',
    hairColor: 'Blond',
    hairLength: 'Lang',
    eyeColor: 'Blau',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: true,
    isSmoker: false,
    description: 'Hi! Ich bin Sarah und mag ehrliche Menschen.',
    latitude: 51.5136,
    longitude: 7.4653, // Dortmund
  },
  {
    email: 'natasha.leipzig@test.com',
    username: 'natasha_leipzig',
    firstName: 'Natasha',
    lastName: 'Ivanova',
    birthDate: '1995-01-20',
    nationalities: ['Russisch'],
    languages: ['Russisch', 'Deutsch', 'Englisch'],
    type: 'Osteuropäisch',
    height: 174,
    weight: 64,
    bodyType: 'Schlank',
    cupSize: 'D',
    hairColor: 'Blond',
    hairLength: 'Sehr lang',
    eyeColor: 'Blau',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: true,
    isSmoker: false,
    description: 'Здравствуйте! Ich bin Natasha aus Leipzig.',
    latitude: 51.3397,
    longitude: 12.3731, // Leipzig
  },
  {
    email: 'lena.hannover@test.com',
    username: 'lena_hannover',
    firstName: 'Lena',
    lastName: 'Wagner',
    birthDate: '1994-10-03',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 166,
    weight: 57,
    bodyType: 'Schlank',
    cupSize: 'B',
    hairColor: 'Braun',
    hairLength: 'Kurz',
    eyeColor: 'Grün',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: false,
    isSmoker: false,
    description: 'Hey! Ich bin Lena - spontan und natürlich.',
    latitude: 52.3759,
    longitude: 9.7320, // Hannover
  },
  {
    email: 'isabella.dresden@test.com',
    username: 'isabella_dresden',
    firstName: 'Isabella',
    lastName: 'Rossi',
    birthDate: '1992-03-28',
    nationalities: ['Italienisch'],
    languages: ['Italienisch', 'Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 171,
    weight: 61,
    bodyType: 'Mittel',
    cupSize: 'C',
    hairColor: 'Schwarz',
    hairLength: 'Lang',
    eyeColor: 'Braun',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: false,
    isSmoker: true,
    description: 'Ciao bella! Sono Isabella da Dresden.',
    latitude: 51.0504,
    longitude: 13.7373, // Dresden
  },
  {
    email: 'mia.bremen@test.com',
    username: 'mia_bremen',
    firstName: 'Mia',
    lastName: 'Hoffmann',
    birthDate: '1998-07-16',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 164,
    weight: 54,
    bodyType: 'Schlank',
    cupSize: 'B',
    hairColor: 'Blond',
    hairLength: 'Schulterlang',
    eyeColor: 'Blau',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: true,
    isSmoker: false,
    description: 'Hi, ich bin Mia aus Bremen!',
    latitude: 53.0793,
    longitude: 8.8017, // Bremen
  },
  {
    email: 'alina.nuernberg@test.com',
    username: 'alina_nuernberg',
    firstName: 'Alina',
    lastName: 'Petrov',
    birthDate: '1996-11-22',
    nationalities: ['Bulgarisch', 'Deutsch'],
    languages: ['Bulgarisch', 'Deutsch', 'Englisch'],
    type: 'Osteuropäisch',
    height: 173,
    weight: 66,
    bodyType: 'Athletisch',
    cupSize: 'D',
    hairColor: 'Braun',
    hairLength: 'Lang',
    eyeColor: 'Grau',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: true,
    isSmoker: false,
    description: 'Здравей! Ich bin Alina aus Nürnberg.',
    latitude: 49.4521,
    longitude: 11.0767, // Nürnberg
  },
  {
    email: 'julia.essen@test.com',
    username: 'julia_essen',
    firstName: 'Julia',
    lastName: 'Koch',
    birthDate: '1993-05-09',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 168,
    weight: 59,
    bodyType: 'Mittel',
    cupSize: 'C',
    hairColor: 'Braun',
    hairLength: 'Schulterlang',
    eyeColor: 'Braun',
    intimateHair: 'Behaart',
    hasTattoos: false,
    hasPiercings: false,
    isSmoker: false,
    description: 'Hallo! Ich bin Julia und mag gemütliche Abende.',
    latitude: 51.4556,
    longitude: 7.0116, // Essen
  },
  {
    email: 'viktoria.freiburg@test.com',
    username: 'viktoria_freiburg',
    firstName: 'Viktoria',
    lastName: 'Becker',
    birthDate: '1991-09-30',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch', 'Französisch'],
    type: 'Westeuropäisch',
    height: 170,
    weight: 62,
    bodyType: 'Mittel',
    cupSize: 'C',
    hairColor: 'Blond',
    hairLength: 'Lang',
    eyeColor: 'Grün',
    intimateHair: 'Total rasiert',
    hasTattoos: true,
    hasPiercings: false,
    isSmoker: true,
    description: 'Salut! Ich bin Viktoria aus Freiburg.',
    latitude: 47.9990,
    longitude: 7.8421, // Freiburg
  },
  {
    email: 'laura.wiesbaden@test.com',
    username: 'laura_wiesbaden',
    firstName: 'Laura',
    lastName: 'Richter',
    birthDate: '1997-02-14',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 165,
    weight: 56,
    bodyType: 'Schlank',
    cupSize: 'B',
    hairColor: 'Rot',
    hairLength: 'Kurz',
    eyeColor: 'Blau',
    intimateHair: 'Total rasiert',
    hasTattoos: false,
    hasPiercings: true,
    isSmoker: false,
    description: 'Hi! Ich bin Laura - lebensfroh und unkompliziert.',
    latitude: 50.0782,
    longitude: 8.2398, // Wiesbaden
  },
  {
    email: 'diana.bonn@test.com',
    username: 'diana_bonn',
    firstName: 'Diana',
    lastName: 'Schulz',
    birthDate: '1995-12-11',
    nationalities: ['Deutsch'],
    languages: ['Deutsch', 'Englisch'],
    type: 'Westeuropäisch',
    height: 172,
    weight: 64,
    bodyType: 'Athletisch',
    cupSize: 'D',
    hairColor: 'Schwarz',
    hairLength: 'Schulterlang',
    eyeColor: 'Braun',
    intimateHair: 'Teilrasiert',
    hasTattoos: true,
    hasPiercings: true,
    isSmoker: false,
    description: 'Hey! Ich bin Diana aus Bonn - sportlich und aktiv.',
    latitude: 50.7374,
    longitude: 7.0982, // Bonn
  },
  {
    email: 'amira.duisburg@test.com',
    username: 'amira_duisburg',
    firstName: 'Amira',
    lastName: 'El-Sayed',
    birthDate: '1994-08-05',
    nationalities: ['Ägyptisch', 'Deutsch'],
    languages: ['Arabisch', 'Deutsch', 'Englisch'],
    type: 'Orientalisch',
    height: 169,
    weight: 60,
    bodyType: 'Kurvig',
    cupSize: 'DD',
    hairColor: 'Schwarz',
    hairLength: 'Sehr lang',
    eyeColor: 'Braun',
    intimateHair: 'Behaart',
    hasTattoos: false,
    hasPiercings: true,
    isSmoker: false,
    description: 'مرحبا! Ich bin Amira - exotisch und geheimnisvoll.',
    latitude: 51.4344,
    longitude: 6.7623, // Duisburg
  },
];

async function seedEscorts() {
  // Erstelle DataSource mit korrigierten Credentials
  const dataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    username: process.env.DB_USERNAME || 'aurora_user',
    password: process.env.DB_PASSWORD || 'aurora_pw',
    database: process.env.DB_DATABASE || 'aurora_db',
    entities: [User],
    synchronize: false,
  });

  try {
    await dataSource.initialize();
    console.log('📦 Verbindung zur Datenbank hergestellt');

    const userRepository = dataSource.getRepository(User);

    // Passwort hashen (für alle: "password123")
    const hashedPassword = await bcrypt.hash('password123', 10);

    let created = 0;
    let skipped = 0;

    for (const escortData of escorts) {
      // Prüfe ob User bereits existiert
      const existingUser = await userRepository.findOne({
        where: { email: escortData.email },
      });

      if (existingUser) {
        console.log(`⏭️  Übersprungen: ${escortData.email} (existiert bereits)`);
        skipped++;
        continue;
      }

      // Erstelle User OHNE Location
      const user = userRepository.create({
        email: escortData.email,
        username: escortData.username,
        password: hashedPassword,
        firstName: escortData.firstName,
        lastName: escortData.lastName,
        role: UserRole.ESCORT,
        birthDate: new Date(escortData.birthDate),
        nationalities: escortData.nationalities,
        languages: escortData.languages,
        type: escortData.type,
        height: escortData.height,
        weight: escortData.weight,
        bodyType: escortData.bodyType,
        cupSize: escortData.cupSize,
        hairColor: escortData.hairColor,
        hairLength: escortData.hairLength,
        eyeColor: escortData.eyeColor,
        intimateHair: escortData.intimateHair,
        hasTattoos: escortData.hasTattoos,
        hasPiercings: escortData.hasPiercings,
        isSmoker: escortData.isSmoker,
        description: escortData.description,
      });

      const savedUser = await userRepository.save(user);

      // Setze Location mit roher SQL-Query (PostGIS ST_SetSRID + ST_MakePoint)
      await dataSource.query(
        `UPDATE users SET location = ST_SetSRID(ST_MakePoint($1, $2), 4326) WHERE id = $3`,
        [escortData.longitude, escortData.latitude, savedUser.id]
      );

      console.log(`✅ Erstellt: ${escortData.firstName} ${escortData.lastName} (${escortData.username})`);
      created++;
    }

    console.log(`\n🎉 Fertig! ${created} Escorts erstellt, ${skipped} übersprungen.`);
    console.log(`🔑 Passwort für alle: password123`);
  } catch (error) {
    console.error('❌ Fehler beim Seeden:', error);
  } finally {
    await dataSource.destroy();
  }
}

seedEscorts();